### ISSUE TITLE
How to setup the .gister?

### ISSUE THREAD

**Issue by thezakman** [tr3buchet/gister#15]
Noob question but i'm not having any luck here. 
:+1:

**Comment by thezakman** [comment]
echo "test" | gister -p
Traceback (most recent call last):
  File "/usr/local/bin/gister", line 11, in <module>
    sys.exit(print_gist_url())
  File "/usr/local/lib/python2.7/dist-packages/gister/gister.py", line 194, in print_gist_url
    args.files, args.private, args.vim, args.edit))
  File "/usr/local/lib/python2.7/dist-packages/gister/gister.py", line 153, in create_gist
    conf = parse_config()
  File "/usr/local/lib/python2.7/dist-packages/gister/gister.py", line 79, in parse_config
    raise Exception('KEYRING specified in config but '
Exception: KEYRING specified in config but python keyring package not available

**Comment by thezakman** [comment]
echo "test" | gister -p
Traceback (most recent call last):
  File "/usr/local/bin/gister", line 11, in <module>
    sys.exit(print_gist_url())
  File "/usr/local/lib/python2.7/dist-packages/gister/gister.py", line 194, in print_gist_url
    args.files, args.private, args.vim, args.edit))
  File "/usr/local/lib/python2.7/dist-packages/gister/gister.py", line 179, in create_gist
    headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))

**Comment by tr3buchet** [comment]
can you post your .gister file, don't forget to sanitize the credentials. also by using the `-p` flag I gather you are intending to create a gist on a private github enterprise implementation, is that correct?

**Comment by tr3buchet** [comment]
marking as closed, reopen if you need additional assistance
